[2024-04-11 12:13:14,810: INFO: config: PyTorch version 2.2.2 available.]
[2024-04-11 12:13:14,810: INFO: config: TensorFlow version 2.13.0 available.]
[2024-04-11 12:13:18,558: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-11 12:13:18,579: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-11 12:13:18,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-11 12:13:18,582: INFO: common: created directory at: artifacts]
[2024-04-11 12:13:18,582: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-11 12:13:18,582: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2024-04-11 12:13:18,713: INFO: data_ingestion: Extraction Compelete]
[2024-04-11 12:13:18,713: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-11 12:13:18,713: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-04-11 12:13:18,713: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-11 12:13:18,729: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-11 12:13:18,730: INFO: common: created directory at: artifacts]
[2024-04-11 12:13:18,731: INFO: common: created directory at: artifacts/data_validation]
[2024-04-11 12:13:18,733: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-04-11 12:13:18,733: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-04-11 12:13:18,737: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-11 12:13:18,739: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-11 12:13:18,740: INFO: common: created directory at: artifacts]
[2024-04-11 12:13:18,741: INFO: common: created directory at: artifacts/data_transformation]
[2024-04-11 12:13:20,762: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-04-11 12:13:20,762: INFO: main: >>>>>> stage Model training stage started <<<<<<]
[2024-04-11 12:13:20,762: ERROR: main: name 'ModeltrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    model_training = ModeltrainingPipeline()
NameError: name 'ModeltrainingPipeline' is not defined
